// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/order.proto

package order_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus represents current order state.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_ACCEPTED    OrderStatus = 1
	OrderStatus_ORDER_STATUS_ISSUED      OrderStatus = 2
	OrderStatus_ORDER_STATUS_RETURNED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_EXPIRED     OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_ACCEPTED",
		2: "ORDER_STATUS_ISSUED",
		3: "ORDER_STATUS_RETURNED",
		4: "ORDER_STATUS_EXPIRED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_ACCEPTED":    1,
		"ORDER_STATUS_ISSUED":      2,
		"ORDER_STATUS_RETURNED":    3,
		"ORDER_STATUS_EXPIRED":     4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// AcceptOrderStatus represents accept result status.
type AcceptOrderStatus int32

const (
	AcceptOrderStatus_ACCEPT_ORDER_STATUS_UNSPECIFIED AcceptOrderStatus = 0
	AcceptOrderStatus_ACCEPT_ORDER_STATUS_ACCEPTED    AcceptOrderStatus = 1
)

// Enum value maps for AcceptOrderStatus.
var (
	AcceptOrderStatus_name = map[int32]string{
		0: "ACCEPT_ORDER_STATUS_UNSPECIFIED",
		1: "ACCEPT_ORDER_STATUS_ACCEPTED",
	}
	AcceptOrderStatus_value = map[string]int32{
		"ACCEPT_ORDER_STATUS_UNSPECIFIED": 0,
		"ACCEPT_ORDER_STATUS_ACCEPTED":    1,
	}
)

func (x AcceptOrderStatus) Enum() *AcceptOrderStatus {
	p := new(AcceptOrderStatus)
	*p = x
	return p
}

func (x AcceptOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcceptOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[1].Descriptor()
}

func (AcceptOrderStatus) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[1]
}

func (x AcceptOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcceptOrderStatus.Descriptor instead.
func (AcceptOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

// Order describes an order entity.
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is a unique identifier of the order.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// user_id is a user identifier.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// status is a current order status.
	Status OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	// created_at is creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// expires_at is expiration time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// issued_at is issue time (optional).
	IssuedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// returned_at is return time (optional).
	ReturnedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=returned_at,json=returnedAt,proto3" json:"returned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Order) GetReturnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReturnedAt
	}
	return nil
}

// GetOrderByIdRequest requests an order by UUID.
type GetOrderByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is order identifier.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByIdRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetOrderByIdResponse returns an order by UUID.
type GetOrderByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResponse) Reset() {
	*x = GetOrderByIdResponse{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResponse) ProtoMessage() {}

func (x *GetOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByIdResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// AcceptOrderRequest accepts an order for a user.
type AcceptOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is order identifier.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// user_id is user identifier.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// expires_at is expiration time.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AcceptOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptOrderRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ReturnOrderRequest returns an order by UUID.
type ReturnOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is order identifier.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnOrderRequest) Reset() {
	*x = ReturnOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnOrderRequest) ProtoMessage() {}

func (x *ReturnOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnOrderRequest.ProtoReflect.Descriptor instead.
func (*ReturnOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// IssueOrderRequest issues an order by UUID.
type IssueOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid is order identifier.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueOrderRequest) Reset() {
	*x = IssueOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueOrderRequest) ProtoMessage() {}

func (x *IssueOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueOrderRequest.ProtoReflect.Descriptor instead.
func (*IssueOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *IssueOrderRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// OrderResponse is a common response for order state changes.
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\x84\x03\n" +
	"\x05Order\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.order.v1.OrderStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06status\x12C\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\tcreatedAt\x12C\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\texpiresAt\x127\n" +
	"\tissued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12;\n" +
	"\vreturned_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"returnedAt\"5\n" +
	"\x13GetOrderByIdRequest\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid\"G\n" +
	"\x14GetOrderByIdResponse\x12/\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05order\"\x9b\x01\n" +
	"\x12AcceptOrderRequest\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12C\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\texpiresAt\"4\n" +
	"\x12ReturnOrderRequest\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid\"3\n" +
	"\x11IssueOrderRequest\x12\x1e\n" +
	"\x04uuid\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid\"\xa4\x01\n" +
	"\rOrderResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.order.v1.OrderStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06status\x12\x1e\n" +
	"\x04uuid\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\x04uuid:8\x92A5\n" +
	"3J1{\"status\":\"ORDER_STATUS_RETURNED\",\"uuid\":\"12345\"}*\x94\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x01\x12\x17\n" +
	"\x13ORDER_STATUS_ISSUED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_RETURNED\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_EXPIRED\x10\x04*Z\n" +
	"\x11AcceptOrderStatus\x12#\n" +
	"\x1fACCEPT_ORDER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cACCEPT_ORDER_STATUS_ACCEPTED\x10\x012\xb6\x03\n" +
	"\fOrderService\x12k\n" +
	"\fGetOrderById\x12\x1d.order.v1.GetOrderByIdRequest\x1a\x1e.order.v1.GetOrderByIdResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/order/{uuid}\x12e\n" +
	"\vAcceptOrder\x12\x1c.order.v1.AcceptOrderRequest\x1a\x17.order.v1.OrderResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/order/accept\x12i\n" +
	"\vReturnOrder\x12\x1c.order.v1.ReturnOrderRequest\x1a\x17.order.v1.OrderResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/order/return/{uuid}\x12g\n" +
	"\n" +
	"IssueOrder\x12\x1b.order.v1.IssueOrderRequest\x1a\x17.order.v1.OrderResponse\"#\x82\xd3\xe4\x93\x02\x1d2\x1b/api/v1/order/return/{uuid}B1Z/github.com/nxlak/go-pvz/proto/order/v1;order_v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: order.v1.OrderStatus
	(AcceptOrderStatus)(0),        // 1: order.v1.AcceptOrderStatus
	(*Order)(nil),                 // 2: order.v1.Order
	(*GetOrderByIdRequest)(nil),   // 3: order.v1.GetOrderByIdRequest
	(*GetOrderByIdResponse)(nil),  // 4: order.v1.GetOrderByIdResponse
	(*AcceptOrderRequest)(nil),    // 5: order.v1.AcceptOrderRequest
	(*ReturnOrderRequest)(nil),    // 6: order.v1.ReturnOrderRequest
	(*IssueOrderRequest)(nil),     // 7: order.v1.IssueOrderRequest
	(*OrderResponse)(nil),         // 8: order.v1.OrderResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_order_v1_order_proto_depIdxs = []int32{
	0,  // 0: order.v1.Order.status:type_name -> order.v1.OrderStatus
	9,  // 1: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: order.v1.Order.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 3: order.v1.Order.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 4: order.v1.Order.returned_at:type_name -> google.protobuf.Timestamp
	2,  // 5: order.v1.GetOrderByIdResponse.order:type_name -> order.v1.Order
	9,  // 6: order.v1.AcceptOrderRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: order.v1.OrderResponse.status:type_name -> order.v1.OrderStatus
	3,  // 8: order.v1.OrderService.GetOrderById:input_type -> order.v1.GetOrderByIdRequest
	5,  // 9: order.v1.OrderService.AcceptOrder:input_type -> order.v1.AcceptOrderRequest
	6,  // 10: order.v1.OrderService.ReturnOrder:input_type -> order.v1.ReturnOrderRequest
	7,  // 11: order.v1.OrderService.IssueOrder:input_type -> order.v1.IssueOrderRequest
	4,  // 12: order.v1.OrderService.GetOrderById:output_type -> order.v1.GetOrderByIdResponse
	8,  // 13: order.v1.OrderService.AcceptOrder:output_type -> order.v1.OrderResponse
	8,  // 14: order.v1.OrderService.ReturnOrder:output_type -> order.v1.OrderResponse
	8,  // 15: order.v1.OrderService.IssueOrder:output_type -> order.v1.OrderResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		EnumInfos:         file_order_v1_order_proto_enumTypes,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
