version: '3'

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.25.3'
  GOLANGCI_LINT_VERSION: 'v2.6.2'
  GCI_VERSION: 'v0.13.7'
  GOFUMPT_VERSION: 'v0.9.2'
  OGEN_VERSION: 'v1.18.0'
  YQ_VERSION: 'v4.49.2'

  # Используем относительные пути, чтобы не ломать Windows-пути
  BIN_DIR: './bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'

  OPEN_API_ORDER_V1_BASE: './api/order/v1/order.openapi.yaml'
  OPEN_API_ORDER_V1_BUNDLE: './api/bundles/order.openapi.v1.bundle.yaml'
  OPEN_API_FILES: './api/bundles'

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          mkdir -p {{.BIN_DIR}}
          go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
      - |
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          mkdir -p {{.BIN_DIR}}
          go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/olezhek28/microservices-course-examples/)" {} +

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          mkdir -p {{.BIN_DIR}}
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install-golangci-lint ]
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml'

  redocly-cli:install:
    desc: Установить локально Redocly CLI
    cmds:
      - |
        echo "📦 Устанавливаем redocly-cli (npm install)..."
        npm install

  redocly-cli:order-v1-bundle:
    desc: Собрать OpenAPI в один файл через redocly (npx)
    deps: [ redocly-cli:install ]
    cmds:
      - npx @redocly/cli bundle {{.OPEN_API_ORDER_V1_BASE}} -o {{.OPEN_API_ORDER_V1_BUNDLE}}

  redocly-cli:bundle:
    desc: Собрать все схемы OpenAPI в общие файлы через redocly
    cmds:
      - task: redocly-cli:order-v1-bundle

  ogen:install:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          echo "📦 Устанавливаем ogen {{.OGEN_VERSION}}..."
          mkdir -p {{.BIN_DIR}}
          go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }

  ogen:gen:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ ogen:install, yq:install ]
    cmds:
      - task: redocly-cli:bundle
      - |
        for ext in yaml yml; do
          find {{.OPEN_API_FILES}} -name "*.${ext}" | while read -r file; do
            if [ -f "$file" ]; then
              has_ogen=$({{.YQ}} e 'has("x-ogen")' "$file")
              if [ "$has_ogen" = "true" ]; then
                echo "🚀 Generating from: $file"
                target=$({{.YQ}} e '."x-ogen".target' "$file")
                package=$({{.YQ}} e '."x-ogen".package' "$file")
                echo "📁 Target: $target"
                echo "📦 Package: $package"
                {{.OGEN}} \
                  --target "$target" \
                  --package "$package" \
                  --clean \
                  "$file" || exit 1
              fi
            fi
          done
        done

  yq:install:
    desc: "Устанавливает yq в bin/ при необходимости"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Installing yq...'
          mkdir -p {{.BIN_DIR}}
          go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }
    status:
      - test -x {{.YQ}}
