// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *AppErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AcceptOrderBadRequest AppError

func (*AcceptOrderBadRequest) acceptOrderRes() {}

type AcceptOrderInternalServerError AppError

func (*AcceptOrderInternalServerError) acceptOrderRes() {}

// Ref: #/components/schemas/app_error
type AppError struct {
	// Код бизнес-ошибки (например, ORDER_NOT_FOUND).
	Code string `json:"code"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
	// Дополнительные параметры ошибки (контекст).
	Fields OptAppErrorFields `json:"fields"`
}

// GetCode returns the value of Code.
func (s *AppError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *AppError) GetMessage() string {
	return s.Message
}

// GetFields returns the value of Fields.
func (s *AppError) GetFields() OptAppErrorFields {
	return s.Fields
}

// SetCode sets the value of Code.
func (s *AppError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *AppError) SetMessage(val string) {
	s.Message = val
}

// SetFields sets the value of Fields.
func (s *AppError) SetFields(val OptAppErrorFields) {
	s.Fields = val
}

// Дополнительные параметры ошибки (контекст).
type AppErrorFields map[string]jx.Raw

func (s *AppErrorFields) init() AppErrorFields {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// AppErrorStatusCode wraps AppError with StatusCode.
type AppErrorStatusCode struct {
	StatusCode int
	Response   AppError
}

// GetStatusCode returns the value of StatusCode.
func (s *AppErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *AppErrorStatusCode) GetResponse() AppError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *AppErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *AppErrorStatusCode) SetResponse(val AppError) {
	s.Response = val
}

type GetOrderByIdBadRequest AppError

func (*GetOrderByIdBadRequest) getOrderByIdRes() {}

type GetOrderByIdInternalServerError AppError

func (*GetOrderByIdInternalServerError) getOrderByIdRes() {}

type GetOrderByIdNotFound AppError

func (*GetOrderByIdNotFound) getOrderByIdRes() {}

// NewOptAppErrorFields returns new OptAppErrorFields with value set to v.
func NewOptAppErrorFields(v AppErrorFields) OptAppErrorFields {
	return OptAppErrorFields{
		Value: v,
		Set:   true,
	}
}

// OptAppErrorFields is optional AppErrorFields.
type OptAppErrorFields struct {
	Value AppErrorFields
	Set   bool
}

// IsSet returns true if OptAppErrorFields was set.
func (o OptAppErrorFields) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAppErrorFields) Reset() {
	var v AppErrorFields
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAppErrorFields) SetTo(v AppErrorFields) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAppErrorFields) Get() (v AppErrorFields, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAppErrorFields) Or(d AppErrorFields) AppErrorFields {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order
type Order struct {
	// Уникальный идентификатор заказа.
	ID string `json:"id"`
	// Идентификатор пользователя, оформившего заказ.
	UserID string `json:"user_id"`
	// Статус заказа.
	Status OrderStatus `json:"status"`
	// Время создания заказа.
	CreatedAt time.Time `json:"created_at"`
	// Время истечения срока действия заказа.
	ExpiresAt OptNilDateTime `json:"expires_at"`
	// Время, когда заказ был выдан.
	IssuedAt OptNilDateTime `json:"issued_at"`
	// Время возврата заказа.
	ReturnedAt OptNilDateTime `json:"returned_at"`
}

// GetID returns the value of ID.
func (s *Order) GetID() string {
	return s.ID
}

// GetUserID returns the value of UserID.
func (s *Order) GetUserID() string {
	return s.UserID
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Order) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Order) GetExpiresAt() OptNilDateTime {
	return s.ExpiresAt
}

// GetIssuedAt returns the value of IssuedAt.
func (s *Order) GetIssuedAt() OptNilDateTime {
	return s.IssuedAt
}

// GetReturnedAt returns the value of ReturnedAt.
func (s *Order) GetReturnedAt() OptNilDateTime {
	return s.ReturnedAt
}

// SetID sets the value of ID.
func (s *Order) SetID(val string) {
	s.ID = val
}

// SetUserID sets the value of UserID.
func (s *Order) SetUserID(val string) {
	s.UserID = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Order) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Order) SetExpiresAt(val OptNilDateTime) {
	s.ExpiresAt = val
}

// SetIssuedAt sets the value of IssuedAt.
func (s *Order) SetIssuedAt(val OptNilDateTime) {
	s.IssuedAt = val
}

// SetReturnedAt sets the value of ReturnedAt.
func (s *Order) SetReturnedAt(val OptNilDateTime) {
	s.ReturnedAt = val
}

func (*Order) acceptOrderRes()  {}
func (*Order) getOrderByIdRes() {}
func (*Order) updateOrderRes()  {}

// Статус заказа.
type OrderStatus string

const (
	OrderStatusACCEPTED OrderStatus = "ACCEPTED"
	OrderStatusISSUED   OrderStatus = "ISSUED"
	OrderStatusRETURNED OrderStatus = "RETURNED"
	OrderStatusEXPIRED  OrderStatus = "EXPIRED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusACCEPTED,
		OrderStatusISSUED,
		OrderStatusRETURNED,
		OrderStatusEXPIRED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusACCEPTED:
		return []byte(s), nil
	case OrderStatusISSUED:
		return []byte(s), nil
	case OrderStatusRETURNED:
		return []byte(s), nil
	case OrderStatusEXPIRED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusACCEPTED:
		*s = OrderStatusACCEPTED
		return nil
	case OrderStatusISSUED:
		*s = OrderStatusISSUED
		return nil
	case OrderStatusRETURNED:
		*s = OrderStatusRETURNED
		return nil
	case OrderStatusEXPIRED:
		*s = OrderStatusEXPIRED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/patch_order_request
type PatchOrderRequest struct {
	// Order's status.
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *PatchOrderRequest) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *PatchOrderRequest) SetStatus(val string) {
	s.Status = val
}

type ReturnOrderInternalServerError AppError

func (*ReturnOrderInternalServerError) returnOrderRes() {}

// ReturnOrderNoContent is response for ReturnOrder operation.
type ReturnOrderNoContent struct{}

func (*ReturnOrderNoContent) returnOrderRes() {}

type ReturnOrderNotFound AppError

func (*ReturnOrderNotFound) returnOrderRes() {}

type UpdateOrderBadRequest AppError

func (*UpdateOrderBadRequest) updateOrderRes() {}

type UpdateOrderInternalServerError AppError

func (*UpdateOrderInternalServerError) updateOrderRes() {}

type UpdateOrderNotFound AppError

func (*UpdateOrderNotFound) updateOrderRes() {}

// Ref: #/components/schemas/update_order_request
type UpdateOrderRequest struct {
	// Identifier of the user who accepts the order.
	UserID string `json:"user_id"`
	// Expiration time for the order (RFC 3339 / ISO 8601).
	ExpiresAt time.Time `json:"expires_at"`
}

// GetUserID returns the value of UserID.
func (s *UpdateOrderRequest) GetUserID() string {
	return s.UserID
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *UpdateOrderRequest) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetUserID sets the value of UserID.
func (s *UpdateOrderRequest) SetUserID(val string) {
	s.UserID = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *UpdateOrderRequest) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}
