// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcceptOrder implements AcceptOrder operation.
//
// Accept order.
//
// PUT /api/v1/order/{id}
func (UnimplementedHandler) AcceptOrder(ctx context.Context, req *UpdateOrderRequest, params AcceptOrderParams) (r AcceptOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderById implements GetOrderById operation.
//
// Get order data by id.
//
// GET /api/v1/order/{id}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReturnOrder implements ReturnOrder operation.
//
// Return (delete) order by id.
//
// DELETE /api/v1/order/{id}
func (UnimplementedHandler) ReturnOrder(ctx context.Context, params ReturnOrderParams) (r ReturnOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
