// Code generated by ogen, DO NOT EDIT.
package order_v1

type AcceptOrderRes interface {
	acceptOrderRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type ReturnOrderRes interface {
	returnOrderRes()
}

type UpdateOrderRes interface {
	updateOrderRes()
}
