// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AcceptOrder implements AcceptOrder operation.
	//
	// Accept order.
	//
	// PUT /api/v1/order/{id}
	AcceptOrder(ctx context.Context, req *UpdateOrderRequest, params AcceptOrderParams) (AcceptOrderRes, error)
	// GetOrderById implements GetOrderById operation.
	//
	// Get order data by id.
	//
	// GET /api/v1/order/{id}
	GetOrderById(ctx context.Context, params GetOrderByIdParams) (GetOrderByIdRes, error)
	// ReturnOrder implements ReturnOrder operation.
	//
	// Return (delete) order by id.
	//
	// DELETE /api/v1/order/{id}
	ReturnOrder(ctx context.Context, params ReturnOrderParams) (ReturnOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
