// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) acceptOrderRes()  {}
func (*BadRequestError) getOrderByIdRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) acceptOrderRes()  {}
func (*InternalServerError) getOrderByIdRes() {}
func (*InternalServerError) returnOrderRes()  {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) getOrderByIdRes() {}
func (*NotFoundError) returnOrderRes()  {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order
type Order struct {
	// Уникальный идентификатор заказа.
	ID string `json:"id"`
	// Идентификатор пользователя, оформившего заказ.
	UserID string `json:"user_id"`
	// Статус заказа.
	Status OrderStatus `json:"status"`
	// Время создания заказа.
	CreatedAt time.Time `json:"created_at"`
	// Время истечения срока действия заказа.
	ExpiresAt OptNilDateTime `json:"expires_at"`
	// Время, когда заказ был выдан.
	IssuedAt OptNilDateTime `json:"issued_at"`
	// Время возврата заказа.
	ReturnedAt OptNilDateTime `json:"returned_at"`
}

// GetID returns the value of ID.
func (s *Order) GetID() string {
	return s.ID
}

// GetUserID returns the value of UserID.
func (s *Order) GetUserID() string {
	return s.UserID
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Order) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *Order) GetExpiresAt() OptNilDateTime {
	return s.ExpiresAt
}

// GetIssuedAt returns the value of IssuedAt.
func (s *Order) GetIssuedAt() OptNilDateTime {
	return s.IssuedAt
}

// GetReturnedAt returns the value of ReturnedAt.
func (s *Order) GetReturnedAt() OptNilDateTime {
	return s.ReturnedAt
}

// SetID sets the value of ID.
func (s *Order) SetID(val string) {
	s.ID = val
}

// SetUserID sets the value of UserID.
func (s *Order) SetUserID(val string) {
	s.UserID = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Order) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *Order) SetExpiresAt(val OptNilDateTime) {
	s.ExpiresAt = val
}

// SetIssuedAt sets the value of IssuedAt.
func (s *Order) SetIssuedAt(val OptNilDateTime) {
	s.IssuedAt = val
}

// SetReturnedAt sets the value of ReturnedAt.
func (s *Order) SetReturnedAt(val OptNilDateTime) {
	s.ReturnedAt = val
}

func (*Order) acceptOrderRes()  {}
func (*Order) getOrderByIdRes() {}

// Статус заказа.
type OrderStatus string

const (
	OrderStatusACCEPTED OrderStatus = "ACCEPTED"
	OrderStatusISSUED   OrderStatus = "ISSUED"
	OrderStatusRETURNED OrderStatus = "RETURNED"
	OrderStatusEXPIRED  OrderStatus = "EXPIRED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusACCEPTED,
		OrderStatusISSUED,
		OrderStatusRETURNED,
		OrderStatusEXPIRED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusACCEPTED:
		return []byte(s), nil
	case OrderStatusISSUED:
		return []byte(s), nil
	case OrderStatusRETURNED:
		return []byte(s), nil
	case OrderStatusEXPIRED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusACCEPTED:
		*s = OrderStatusACCEPTED
		return nil
	case OrderStatusISSUED:
		*s = OrderStatusISSUED
		return nil
	case OrderStatusRETURNED:
		*s = OrderStatusRETURNED
		return nil
	case OrderStatusEXPIRED:
		*s = OrderStatusEXPIRED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ReturnOrderNoContent is response for ReturnOrder operation.
type ReturnOrderNoContent struct{}

func (*ReturnOrderNoContent) returnOrderRes() {}

// Ref: #/components/schemas/update_order_request
type UpdateOrderRequest struct {
	// Identifier of the user who accepts the order.
	UserID string `json:"user_id"`
	// Expiration time for the order (RFC 3339 / ISO 8601).
	ExpiresAt time.Time `json:"expires_at"`
}

// GetUserID returns the value of UserID.
func (s *UpdateOrderRequest) GetUserID() string {
	return s.UserID
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *UpdateOrderRequest) GetExpiresAt() time.Time {
	return s.ExpiresAt
}

// SetUserID sets the value of UserID.
func (s *UpdateOrderRequest) SetUserID(val string) {
	s.UserID = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *UpdateOrderRequest) SetExpiresAt(val time.Time) {
	s.ExpiresAt = val
}
