// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AcceptOrderOperation  OperationName = "AcceptOrder"
	GetOrderByIdOperation OperationName = "GetOrderById"
	ReturnOrderOperation  OperationName = "ReturnOrder"
)
